languages:
  Python: true
engines:
  pep8:
    enabled: true
    checks:
        E501:
            enabled: false
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
exclude_paths:
    - versioneer.py
    - bluepyopt/_version.py
    - docs/source/conf.py
    - bluepyopt/tests
    - examples
