language: python
matrix:
    include:
        - python: 2.7
        - python: 3.6
        - python: 3.7
        - python: 3.8
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/6129e0ab91805bbac8c1
    on_success: change
    on_failure: change
    on_start: false
cache:
    pip: true
    directories:
      - "$TRAVIS_BUILD_DIR/.tox"
git:
  depth: 2147483647
before_install: 
  - pip install pip --upgrade
  - pip install tox --upgrade
  - pip install codecov
script: tox -e "$(echo py$TRAVIS_PYTHON_VERSION | tr -d .)-unit-functional-style-syntax"
after_success:
  - codecov
addons:
  code_climate:
    repo_token: 94713078b6ae3fe8344e80649ea189e2e0d0cb78e707edf169b3ff9d3765da46
