language: python
matrix:
    include:
        - python: 2.7
        - python: 3.6
        - python: 3.7
        - python: 3.8
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/6129e0ab91805bbac8c1
    on_success: change
    on_failure: change
    on_start: false
cache:
    pip: true
    directories:
      - "$TRAVIS_BUILD_DIR/.tox"
git:
  depth: 2147483647
