language: python
python:
    - '2.7'
    - '3.6'
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
install: pip install pip --upgrade
script: make test
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/6129e0ab91805bbac8c1
    on_success: change
    on_failure: change
    on_start: false
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/local"
  - "$HOME/src"
git:
  depth: 2147483647
deploy:
  provider: pypi
  user: wvangeit
  password:
    secure: B5wyxcjPTa8KDE6HZ/5f/yj7F/qzTDWa7GS0b7xqn/vvBxyWTdYwnjNOD7VDNmZ3U46zV8UGTSZDV0MDiIoKamnWZAaJEHg9tEyFl/74rGtWq2k7eYC/qt+I2r68DDeEBDf6kErgcpKJzQ4FyzUcNjVlvtqRNowCcdpU0ViwIRNWDTdOxMaeQz9pwlSK00oF2clNRrnDmMfsq03zOmn49PNMf80tFqZ8CpLBH/Dbbar8LIxpr5qCyDz/OUZKl2cmH2dg95cA9RIjVzA07m1+TXLwrRkeC4lShKUKv4FdCzVdiFTtaZlKOaJRHewaLdv8huPzUcFFkDMbe7bf1RNzeBAeHcQcp/Y8bhg0ZXtyo+aqCsOIDGN7mLCBzbojO+f20+t5jJ6bLe27CQL5UCWFXwElTMdgFczTgnN1UFj4qr86tHtu64E2SnavkCldtoi5XcAagtEIrxujBCjCoccmPk5oqUfT62dw92SCm2/NZTgn6qGVZCCucFXd7V2lnxPp26NMnTce46p2fZuNDiSIhijVnx6dW/WgwAWWgk7/mgeQaZG4d2+YznoGAaDbFO/anunSD/KOvNwgFJjjKddkCPqgcIrXS5NQHq60rTkdyajDDSCqYPNSntXp+qbLCHd9Ty7bs8L111ede9o3X4fFo44sT825obVSR4+lYHEdefs=
  on:
    condition: "$TRAVIS_EVENT_TYPE != cron && $TRAVIS_PYTHON_VERSION == 2.7"
before_install:
- pip install codecov
before_script:
- SRC_DIR=$HOME/local/src
- NRN_INSTALL_DIR=$HOME/local/nrn
- "./.travis_install_neuron.sh ${SRC_DIR} ${NRN_INSTALL_DIR}"
- export PATH=$PATH:${NRN_INSTALL_DIR}/x86_64/bin
- export PYTHONPATH=$PYTHONPATH:${NRN_INSTALL_DIR}/lib/python
after_success:
- codecov
addons:
  code_climate:
    repo_token: 94713078b6ae3fe8344e80649ea189e2e0d0cb78e707edf169b3ff9d3765da46
